### ISSUE TITLE
Fusion Calculation Incorrect

### ISSUE THREAD

**Issue by Alenael** [oceanxdds/dx2_fusion#2]
Some demons fusion calculations are not correctly setup.

Example:
Deity + Lady = Megami

I cannot read Japanese but below we should have this one available in the list for Megami fusions. This is around line 104 in devil_raw_data.js I will update with others should I or others find them.

 name:'女神',
        name_tw:'女神',
        name_en:'Megami',
        highlight:false,
        formulas:[
            ['靈鳥','大天使'],
            ['魔神','靈鳥'],
            ['聖獸','大天使'],
            ['聖獸','神獸'],
            ['幻魔','靈鳥'],
            ['龍神','天使'],
            ['地母神','魔神'],
            ['地母神','幻魔'],
            ['天使','大天使'],
            ['墮天使','天使'],
            ['鬼女','大天使'],
            ['鬼女','神獸'],
            ['鬼女','地母神'],
            ['鬼女','妖精']
        ],

Source: https://d2-megaten-l.sega.com/en/sp/news/detail/068839.html

**Comment by oceanxdds** [comment]
The example, Deity + Lady = Megami, is already in the list. 
...
['地母神','魔神'], // ['Lady','Deity']
...
You can check this rule in calculator by click button 'Reverse Fusion' on demon 'Magami Lakshmi' : )

**Comment by Alenael** [comment]
So the specific issue is that Pallas Athena shows 0 fusions possible from 3+3 but she has many possible fusions for 3+3.  Why would these not show up by default when looking at fusables for a demon? Its either a bug in the game itself that is allowing her to be fused, an issue with the site that is not showing the 3+3, or something to do with free demons handed out that have higher grade than normal as far as I can tell.

Ose + Virtue
Kresnik + Feng
Feng + Horus
etc.

![Screenshot_2019-06-24-22-41-14-324](https://user-images.githubusercontent.com/46180324/60217399-a11bf580-983a-11e9-828a-d6293fb0bbf6.jpg)

**Comment by oceanxdds** [comment]
Thanks for your information ! It's a bug ! :"D
A new non-fusible demon "Megami Parvati" cause this issue, and I have fix it.
Please kindly check calculator again with version 190627

**Comment by Alenael** [comment]
Thanks looks like its back to normal now. I will let you know should we find anything else thanks!
