### ISSUE TITLE
Feature Request - Parameters directly to fusible demons

### ISSUE THREAD

**Issue by Alenael** [oceanxdds/dx2_fusion#21]
I want to add a link for all demons on the [Dx2 Wiki](https://dx2wiki.com/) and the [Discord Bot](https://github.com/Alenael/Dx2-DiscordBot) that digs directly into each demons Normal and Reverse fusions without needing to navigate to the page, search for the demon, etc. 

Do you have any available URL where we can pass in some parameters (English names and reverse or normal) and dig straight down into that specific demon?

Below is an example of the URL and the expected state I would want to get into.

https://oceanxdds.github.io/dx2_fusion/#en?fusionMode=Normal&Demon=Baal
![image](https://user-images.githubusercontent.com/46180324/75083027-922e3580-54e4-11ea-83d3-b46fa5b84bba.png)

https://oceanxdds.github.io/dx2_fusion/#en?fusionMode=Reverse&Demon=Zhong+Kui
![image](https://user-images.githubusercontent.com/46180324/75082986-55623e80-54e4-11ea-9d94-0ff095fbf295.png)

I don't care how the URL looks as long as I can form it with the English name of the demon and Reverse/Normal in some way. We also would like to make sure it sets up the language as English using the #en switch available. 

The English names we would be sending to the URL would come from the [Dx2 DB](https://github.com/Alenael/Dx2DB) we maintain. We may find some issues with the English names in your data as we set this up but we'll let you know in separate issues if that occurs and ask for en name corrections.

If the URL was malformed and could not find needed info just return them to the apps original state.

Please let me know if you have have any additional questions about this.

**Comment by oceanxdds** [comment]
It's cool idea, please try the new version 200222 : D

Parameters:
route = 'fission' (reverse) or 'fusion' (normal)
demon = the name of demon (support multi-language)
race = (optional) the name of demon's race (support multi-language)

Case 1
before https://oceanxdds.github.io/dx2_fusion/#en?fusionMode=Normal&Demon=Baal
after https://oceanxdds.github.io/dx2_fusion/?route=fusion&demon=Baal#en

Case 2
before https://oceanxdds.github.io/dx2_fusion/#en?fusionMode=Reverse&Demon=Zhong+Kui
after https://oceanxdds.github.io/dx2_fusion/?route=fission&demon=Zhong%20Kui#en

**Comment by Alenael** [comment]
Nice! This will work perfectly. I will add support to those tools thanks!

**Comment by Alenael** [comment]
Thanks for the fast update everyone is already using and enjoying the ease of getting to where they need to go!
