### ISSUE TITLE
Looking To Default To English

### ISSUE THREAD

**Issue by Alenael** [oceanxdds/dx2_fusion#4]
We would like to drop us hosting a version of this site for English speakers and instead point our URL right to the site itself. The issue we have though is that English isn't a default language and causes confusion for users who enter the site and must navigate to the Settings and change it to English. 

Could we get a URL switch or something that can set the site into English (And other languages)? Another option we could take is a to be able to change the default language to English via a value in a file so that we can deploy your project to a web server and flip a variable in a config somewhere to default it to English.

**Comment by oceanxdds** [comment]
Like this ?

https://oceanxdds.github.io/dx2_fusion/#en

Alenael <notifications@github.com> 於 2019年8月29日 週四 01:46 寫道：

**Comment by Alenael** [comment]
I will take a look into pointing us at that URL then.

Thanks!
