### ISSUE TITLE
Missing reverse fusion path for some multi-fusions

### ISSUE THREAD

**Issue by squeakyrino** [oceanxdds/dx2_fusion#40]
The following multi-fusions are missing their reverse fusion path:
- Tyrant Tzitzimitl
- Megami Anat

**Comment by oceanxdds** [comment]
Thank for your feedback! Please check version 200718 : D

**Comment by squeakyrino** [comment]
> Thank for your feedback! Please check version 200718 : D

Thanks you very much! ❤️

**Comment by squeakyrino** [comment]
I just noticed the mag calculation is broken for both of them however.
![image](https://user-images.githubusercontent.com/25160630/87852222-0b954d00-c8f8-11ea-97f0-7da162fd0a31.png)
![image](https://user-images.githubusercontent.com/25160630/87852225-1223c480-c8f8-11ea-9b03-00a6eee0f038.png)

**Comment by oceanxdds** [comment]
Oops, sorry I forgot to check it! OK now, please try again : D

**Comment by squeakyrino** [comment]
> Oops, sorry I forgot to check it! OK now, please try again : D

Seem to be working! Thank you very much again! ❤️
