### ISSUE TITLE
Incorrect Skill Points required for transfer.

### ISSUE THREAD

**Issue by squeakyrino** [oceanxdds/dx2_fusion#44]
The skill Enduring Soul says it needs 18 points for transfering in the website but it's 12 in-game.

Website:
![image](https://user-images.githubusercontent.com/25160630/88399144-50205d00-cdbe-11ea-9337-a8d23d537c8d.png)

In-game:
![image](https://user-images.githubusercontent.com/25160630/88399103-40087d80-cdbe-11ea-98df-47f08571cc6b.png)

**Comment by oceanxdds** [comment]
Thanks for your feedback! Please check version 200724 : D

**Comment by squeakyrino** [comment]
It shows up correctly now! Thank you!
