### ISSUE TITLE
Missing formulas

### ISSUE THREAD

**Issue by ara-op** [oceanxdds/dx2_fusion#5]
Hi,
We've found a small number of formulas that are missing from the fusion simulator. These are (in English and Japanese):

**Megami (女神):**
Jaki, Haunt
['邪鬼','幽鬼']

**Kishin (鬼神):**
Jaki, Foul
['邪鬼','外道']

**Yoma (妖魔):**
Jaki, Night
['邪鬼','夜魔']

**Beast (魔獸):**
Jaki, Wilder
['邪鬼','妖獸']

**Vile (邪神):**
Jaki, Fallen
Jaki, Tyrant
['邪鬼','墮天使']
['邪鬼','魔王']

**Haunt (幽鬼):**
Jaki, Brute
Jaki, Femme
Jaki, Vile
['邪鬼','妖鬼']
['邪鬼','鬼女']
['邪鬼','邪神']

Thank you for creating and updating this tool, it's very useful.

**Comment by oceanxdds** [comment]
These combinations have been updated. Thanks for your information. :D

**Comment by ara-op** [comment]
Thank you!
