### ISSUE TITLE
Add Event Demons

### ISSUE THREAD

**Issue by Maaster** [oceanxdds/dx2_fusion#7]
Any chance you could also add the Event Demons?
Helper Frost and Halloween Jack are the most important Id guess, as we will get spares this week. People would probably like to see what they can fuse with the spares.

Else theres Nadja, Kabuso and Jack the Ripper, though those arent worth it for fusion Id assume, so I wouldnt mind if you dont add them.

**Comment by oceanxdds** [comment]
I just add 10 demons which including event demons. Please kindly check version 191027 : D

**Comment by Maaster** [comment]
Thanks for the update :) I notice that Halloween Jack is still missing, can you add him too?

![image](https://user-images.githubusercontent.com/6342894/67636097-225cc500-f8cd-11e9-8d22-604cc4d98eff.png)

**Comment by oceanxdds** [comment]
Halloween Jack has been added ! : D

**Comment by Maaster** [comment]
Great work, thanks :)

**Comment by Maaster** [comment]
Ah, I just now realized that you only implemented the demons and its skills. 

As these demons can be fused into thers, would it be possible for you to also add the fusion paths of Halloween Jack and Helper Frost?

For example: Helper Frost + Prometheus = Lilith

**Comment by oceanxdds** [comment]
Done! : D
![image](https://user-images.githubusercontent.com/12458109/68075832-5d3c8c80-fde8-11e9-9fb5-b98b5a0d5390.png)

And I also add auto calculator for multi-fusion.
![image](https://user-images.githubusercontent.com/12458109/68075881-eb187780-fde8-11e9-8aa0-2aaa01c7de73.png)

**Comment by Maaster** [comment]
Thanks :)
