### ISSUE TITLE
Add Wood Race

### ISSUE THREAD

**Issue by Maaster** [oceanxdds/dx2_fusion#79]
Hey! Thanks for the tool again, we all use it a lot in the community.

Im not sure if you are still active in the game (or here), but they will add the wood race.

[Details here](https://d2-megaten-l.sega.com/en/news/detail/087788.html)

So would be great if you could add them. Thanks!

**Comment by oceanxdds** [comment]
Yes, I'm working for it now.
New race "Wood" would be added in 10 Jun.
