### ISSUE TITLE
Add Drake Race & Seraph

### ISSUE THREAD

**Issue by Maaster** [oceanxdds/dx2_fusion#8]
Drakes and Seraph will be released on 7th, would be great to have them added to the fusion calc. 

Link to News: https://d2-megaten-l.sega.com/zh/news/detail/074018.html

**Comment by oceanxdds** [comment]
Just updated !
Please check version 191107. : D

**Comment by Maaster** [comment]
Thanks :) Small thing: Fafnirs Blight Skill has the wrong description (a copy of his Golden Greed Skill).

**Comment by oceanxdds** [comment]
Thanks ! The description has been fixed ! : D
