### ISSUE TITLE
Quick fusion path buttons use Beelzebub (G.97)

### ISSUE THREAD

**Issue by Dydomio** [oceanxdds/dx2_fusion#84]
Hi! The quick fusion path buttons at the top left often use Beelzebub (G.97) as a fusion ingredient, even though Beelzebub does not match the selected base rarity and the resulting fusion is often a downgrade fusion. This occurs regardless of whether the "Downgrade Fusion" setting is set to Allow or Deny. For example, selecting 2* base rarity for fusing a Prometheus results in a fusion path using two Beelzebubs, and selecting either 2* or 1* base rarity for fusing a Tiamat both result in a fusion path of Beelzebub x Nozuchi.

![image](https://user-images.githubusercontent.com/97705947/149420687-3983206a-063a-43ba-839c-fc59c7ce2afc.png)

Thank you so much for making and maintaining this fusion tool, it's a huge help when it comes to fusing demons! :D

**Comment by oceanxdds** [comment]
The bug has been fixed now : D

**Comment by Dydomio** [comment]
Thank you very much! ❤️
