### ISSUE TITLE
Normal Fusion shows Multi-Fusion as result

### ISSUE THREAD

**Issue by Maaster** [oceanxdds/dx2_fusion#9]
Some Demons have a Multi-Fusion shown as the result of a normal fusion:

![image](https://user-images.githubusercontent.com/6342894/68115952-e394c380-fef9-11e9-8c79-6a819bdb7dd2.png)

(This is on Ananta)

**Comment by oceanxdds** [comment]
Thanks for your information! : D
The bug has been fixed. Please refresh and try again. : D

**Comment by Maaster** [comment]
Thanks :)
